### PR TITLE
Fix release build

### LINKED ISSUE #14: `.failing` isn't enclosed in #if DEBUG thus breaks release builds
Enclosing extension in `#if DEBUG` `#endif` will solve it.
https://github.com/pointfreeco/composable-core-location/blob/95c32ab3677023aed0f5eb18c5c312bc31e296cb/Sources/ComposableCoreLocation/Failing.swift#L5

### PR DESCRIPTION
**Pull request by andreyz**
Should fix #14

### CODE REVIEW

**Comment by mbrandonw** [comment]
This shouldn't be necessary because we provide a stubbed implemented of `XCTFail` in non-debug builds:

https://github.com/pointfreeco/xctest-dynamic-overlay/blob/0ec2d710978df8a73ae788b9897d2c189880de0f/Sources/XCTestDynamicOverlay/XCTFail.swift#L74-L94

That was released in [0.2.0](https://github.com/pointfreeco/xctest-dynamic-overlay/releases/tag/0.2.0) of xctest-dynamic-overlay. I believe if you update your packages to their latest versions it should work fine. 

We could do a better job of forcing SPM to pull in 0.2.0 of cutest-dynamic-overlay by [pinning the TCA version](https://github.com/pointfreeco/composable-core-location/blob/95c32ab3677023aed0f5eb18c5c312bc31e296cb/Package.swift#L20) in the library to 0.25.0, which is when TCA bumped to 0.2.0.

What do you think about making that change instead?

**Comment by andreyz** [comment]
> We could do a better job of forcing SPM to pull in 0.2.0 of cutest-dynamic-overlay by [pinning the TCA version](https://github.com/pointfreeco/composable-core-location/blob/95c32ab3677023aed0f5eb18c5c312bc31e296cb/Package.swift#L20) in the library to 0.25.0, which is when TCA bumped to 0.2.0.
> 
> What do you think about making that change instead?

@mbrandonw sounds good!

**Review by mbrandonw — APPROVED** [review]
Awesome, looks good to me but I'll also chat with @stephencelis this morning to see if he agrees.

Thanks!

**Comment by andreyz** [comment]
Ehh! Just realised that we've misunderstood each other and the PR we've merged didn't help fix package building for Release.

The reason why this package fails to build for release is that `Effect.failing` is only defined in Debug, while our earlier discussion was around `XCTFail` (which is indeed stubbed for Release).

I'm ready to make another PR. What's best plan of action: 
- Implement stubbed `Effect.failing` in ComposableCoreLocation or
- Enclose `LocationManager.failing` in `#if DEBUG/#endif`?

**Pull request merged**
